factorio:
  image: talltechdude/rancher-factorio
  ports:
    - 34197:34197/udp
  net: bridge
  environment:
    - FACTORIO_SAVE_NAME=${servername}
  volumes_from:
    - factorio-data
  labels:
    io.rancher.sidekicks: factorio-data

factorio-data:
  image: talltechdude/rancher-factorio
  net: none
  volumes:
    - /opt/factorio/saves
    - /opt/factorio/mods
  command: /bin/true
  labels:
    io.rancher.container.start_once: "true"

factorio-manager:
  image: jjclark/factorio
  environment:
    - ADMIN_PASSWORD=12345678
  ports:
    - 8000:8000/tcp
  links:
    - factorio
  net: bridge
  volumes_from:
    - factorio-data
